"use client";

import React from 'react';

export default function AIAnalytics() {
  return (
    <div className="card">
      <h3 className="text-lg font-medium">AI Analytics</h3>
      <p className="text-sm text-slate-500">Trend detection, anomaly alerts and performance summaries generated by AI.</p>
      <div className="mt-3 h-28 flex items-center justify-center text-slate-400">Analytics charts go here</div>
    </div>
  );
}
